### ISSUE TITLE
Using phaseLD for four-way-cross populations

### ISSUE THREAD

**Issue by cai1991** [plantformatics/phaseLD#2] opened 2020-12-06 13:48 UTC
Hello @plantformatics ,

Thanks for developing phaseLD and I'm now using it to analyze our four-way-cross (FWC) populations data. Construction of the FWC populations: 1) homozygous diploid parent A x parent B, parent C x parent D, 2) two F1s were then crossed ((AxB)*(CxD)) to generate the FWC population. We know the genotypes of parents A, B, C, D and the FWC population and I run phaseLD as you suggested #1 with parameters "--quick_mode --rpen 0.1".

I have some problems/questions, and hope you can provide some insights to solve them. 

- In some chromosomes, I see there is quite a large region with no markers in the *.raw_hap output, like in chr2 from 1.6-36Mb (64Mb in total for chr2). Would it greatly affect the CO identification? And how to avoid it?  
- I have error "Can't take log of 0 at PDL/Stats/GLM.pm line 2057, <DATA> line 90." for quite some chromosomes when running extract_crossovers.pl, which stopped the program. Do you have ideas why it happens and how to solve it?
- In the *.crossoverintervals output, does the fifth column mean the probability of a crossover? And should be filtered with threshold of 0.95 as described in your paper (Genome Biology, 2017)? I also noticed some rows where there are not haplotype shifts like 0=>1 or 1=>0 in the fourth column, but "1". What do these rows mean? 

Thank you in advance and look forward to your reply.

Best regards,
Cai

**Comment by plantformatics** [comment] 2020-12-07 14:31
Hello @cai1991,

I will attempt to address your questions below.

>In some chromosomes, I see there is quite a large region with no markers in the *.raw_hap output, like in chr2 from 1.6-36Mb (64Mb in total for chr2). Would it greatly affect the CO identification? And how to avoid it?

This could be due to:

1. too few markers passing `rpen` thresholds, or
2. initialization of the haplotype chain with poor markers.

This is not unusual, my suggested remedy is to adjust the `rpen` parameter for these chromosomes, trying a gradient to see which threshold gives reasonable results. Trying values up to 0.4 or 0.5 would be reasonable. Another option is to filter the first few markers, or use more stringent criteria for retaining markers, like % missing or allele frequency. Long spans with no markers could also be due to low frequency of heterozygous SNPs in general. Because `phaseLD` needs windows of SNPs and is stringent on retaining markers, regions with many low quality and low frequency hets will tend to get stretched over long physical distances. The algorithm dynamically attempts to extend windows by searching for good quality SNPs until the number of markers satisfying the selection criterion is met. 

Another consideration is that the algorithm heavily relies on quality markers at initialization. If the first few markers are poor quality, the algorithm will attempt to find adjacent markers that are in strong LD with these poor markers, filtering all other SNVs. This can result in error propagation for an entire chromosome. I might check this first. There should be an output log specifying the extent of LD between pairwise markers in a window, it might be useful to check these logs to see if the first few markers are causing error propagation throughout the chain. 

> I have error "Can't take log of 0 at PDL/Stats/GLM.pm line 2057, line 90." for quite some chromosomes when running extract_crossovers.pl, which stopped the program. Do you have ideas why it happens and how to solve it?

Can you send me a subset of input data so I can reproduce the error? 

> In the *.crossoverintervals output, does the fifth column mean the probability of a crossover? And should be filtered with threshold of 0.95 as described in your paper (Genome Biology, 2017)? I also noticed some rows where there are not haplotype shifts like 0=>1 or 1=>0 in the fourth column, but "1". What do these rows mean?

The fifth column denotes the crossover probability, as you have guessed. All rows should have haplotype shifts, can you send me the input (or small subset that is able to reproduce the error) for `extract_crossovers.pl`? My email address can be found on my user page. 

Hope this helps,

Alex

**Comment by cai1991** [comment] 2020-12-07 18:10
Hello @plantformatics ,

Thanks a lot for your very detailed answer. I will try more according to your suggestions. And I just sent you the input data to reproduce the error that I have.

Best regards,
Cai

**Comment by plantformatics** [comment] 2020-12-08 19:05
Hi @cai1991,

An update to `extract_crossovers.pl` should fix the log of 0 and truncated output errors you were seeing. I also made some improvements to the logistic regression models which should enable more reliable crossover detection. Please let me know if further debugging is necessary.  

Cheers,

Alex

**Comment by cai1991** [comment] 2020-12-09 19:11
Hello @plantformatics ,

Thanks for the debugging. So far the new script of `extract_crossovers.pl` goes well. The issue of long spans with no markers also gets improved after removing poor markers in the first few markers. But I still have follow-up questions with regard to the identified CO.

- Case 1:

`C9      19737810        19738465        1=>0    0.999842642446  92      655` 
`C9      51561393        51561631        1=>0    0.99977425779   92      238`
`C9      62050626        62056683        1=>0    0.999847751285  92      6057`
How do I understand the CO for this progeny? Does it mean that there is a haplotype transition (0=>1) from 19.7M to 51.6M which is not able to be identified? Same for the region of 51.6M-62.1M.

- Case 2:

`C9      33172708        33172747        0=>1    0.99986426981   26      39`
`C9      33391979        33397373        1=>0    0.999793733875  26      5394`
`C9      33403427        33404161        0=>1    1       26      734`
`C9      53622756        53623196        1=>0    0.999853626547  26      440`
`C9      53625866        53626067        0=>1    0.999884791668  26      201`
For this progeny, it seems that the first 3 COs take place within a region of 232Kb and the last 2 COs within a region of 3.3Kb. I'm wondering if it would be possible to have a few COs in a short region? Or that might be caused by noisy markers?

In addition, I find the number of CO per chromosome for some progenies are more than expected. Is adjusting the `rpen`  parameter helpful for reducing the number of CO? If (how) a post-filtering can be applied? 

Best regards,
Cai

**Comment by plantformatics** [comment] 2020-12-09 19:46
Hi @cai1991 

>How do I understand the CO for this progeny? Does it mean that there is a haplotype transition (0=>1) from 19.7M to 51.6M which is not able to be identified? Same for the region of 51.6M-62.1M.

Thats how I would interpret this result.

> For this progeny, it seems that the first 3 COs take place within a region of 232Kb and the last 2 COs within a region of 3.3Kb. I'm wondering if it would be possible to have a few COs in a short region? Or that might be caused by noisy markers?

This is typical of resequencing data. The key to reducing these sort of false positives is to first filter by crossover probability (which it looks like you have already done). By best advice is to increase the window size (using `--bwin`) to 100 or even 200 SNVs. Increasing `rpen` to something in the range of 0.3-0.5 will also help. If the SNV window size is too small, artifacts and noisy markers can contribute a large proportion to the haplotype call. These bins are used to narrow the search regions in `extract_crossovers.pl`. If the windows are larger, the chance for bad markers to create fake haplotype transitions is reduced. It would be a good idea to check the average r2 value for each marker using windows. I have a tool for this somewhere, but its locked up in gzipped tar directory. 

Optimizing these parameters for each chromosome and data type is by far the most time consuming aspect of generating a high quality crossover data set. Something that I find extremely helpful is to plot the haplotype calls for all your progeny as a recombination bin map. You can cross-check these global patterns with the crossover data set to make sure they make sense. 

Another thing to look out for is your reference assembly. If there are any inversion, rearrangements or large scale structural variants compared to your genotypes, they will create the illusion of crossovers. You can reorder haplotype bins (raw.bayes) by genetic distance and rerun `extract_crossovers.pl`. The algorithm will explicitly skip crossovers that are not physically adjacent on the reference assembly. This greatly improved the reliability of the crossovers in our study.

Lastly, true crossovers tend to have lots of local haplotype transitions around them that arise from imperfect DNA repair of the crossover junction. If you are getting a cluster of crossovers in one physical area, it may be advisable to merge them all. See an example below:

**true crossover:** 

chr01 1000 2000 0=>1

**predicted crossovers:** 

chr01 1005 1050 0=>1
chr01 1075 1200 1=>0
chr01 1500 1750 0=>1

**merged:**
chr01 1005 1750 0=>1

**Comment by cai1991** [comment] 2020-12-09 20:07
Hi @plantformatics ,

Thank you very much for your detailed explanations. That's very clear and helpful. I will try playing with my data based on your suggestions.

Best regards,
Cai

**Closed as completed** 2020-12-16 16:19 UTC
